
spring:
  datasource:
    url: jdbc:mysql://192.168.56.103:3307/dcc_workflow
    username: root
    password: 123456
    hikari:
      max-lifetime: 870000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.126.com
    username: dcc_helpdesk@126.com
    password: FHNFUOTXFYJKFZCG
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  activiti:
    check-process-definitions: false
    history-level: full
    db-history-used: true
    deployment-mode: never-fail
#    database-schema-update: true
    async-executor-activate: false

  servlet:
    multipart:
      max-file-size: 100MB

logging:
  level:
    org.activiti.engine.impl.persistence.entity: trace
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug



